name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7"]
        gemfile: ["gemfiles/rails6.gemfile"]
        include:
        - ruby: "2.6"
          gemfile: "gemfiles/rails6.gemfile"
        - ruby: "2.7"
          gemfile: "gemfiles/railsmaster.gemfile"
        - ruby: "3.0"
          gemfile: "gemfiles/rails6.gemfile"
    steps:
    - uses: actions/checkout@v2
    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        bundler: 2.2.15
    - name: Run RSpec
      run: |
        bundle exec rspec
